spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cinema_db?characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6389

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
